(source melpa)

(depends-on "auto-complete")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "go-eldoc")
(depends-on "go-mode")
(depends-on "go-snippets")
(depends-on "magit")
(depends-on "pallet")
(depends-on "persistent-soft")
(depends-on "projectile")
(depends-on "smex")
(depends-on "sublime-themes")
(depends-on "ucs-utils")
(depends-on "unicode-fonts")