(require 'company)
(require 'company-go)
(add-hook 'before-save-hook #'gofmt-before-save)
(add-hook 'go-mode-hook (lambda ()
                          (local-set-key (kbd \"M-.\") #'godef-jump)
                          (set (make-local-variable 'company-backends) '(company-go))
                          (company-mode)))
